//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/IA_DuneGameplay.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @IA_DuneGameplay: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @IA_DuneGameplay()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IA_DuneGameplay"",
    ""maps"": [
        {
            ""name"": ""BallControls"",
            ""id"": ""59ec255e-bd89-495f-9789-84c64eda431a"",
            ""actions"": [
                {
                    ""name"": ""DownSprint"",
                    ""type"": ""Value"",
                    ""id"": ""9b70ce8f-bfba-41a2-b576-d142a4474484"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d8ebf819-1866-4351-83b9-9efa63af05a8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e68d77e1-f91c-4dc9-b185-8133ee6fe338"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BallControls
        m_BallControls = asset.FindActionMap("BallControls", throwIfNotFound: true);
        m_BallControls_DownSprint = m_BallControls.FindAction("DownSprint", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BallControls
    private readonly InputActionMap m_BallControls;
    private List<IBallControlsActions> m_BallControlsActionsCallbackInterfaces = new List<IBallControlsActions>();
    private readonly InputAction m_BallControls_DownSprint;
    public struct BallControlsActions
    {
        private @IA_DuneGameplay m_Wrapper;
        public BallControlsActions(@IA_DuneGameplay wrapper) { m_Wrapper = wrapper; }
        public InputAction @DownSprint => m_Wrapper.m_BallControls_DownSprint;
        public InputActionMap Get() { return m_Wrapper.m_BallControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BallControlsActions set) { return set.Get(); }
        public void AddCallbacks(IBallControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_BallControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BallControlsActionsCallbackInterfaces.Add(instance);
            @DownSprint.started += instance.OnDownSprint;
            @DownSprint.performed += instance.OnDownSprint;
            @DownSprint.canceled += instance.OnDownSprint;
        }

        private void UnregisterCallbacks(IBallControlsActions instance)
        {
            @DownSprint.started -= instance.OnDownSprint;
            @DownSprint.performed -= instance.OnDownSprint;
            @DownSprint.canceled -= instance.OnDownSprint;
        }

        public void RemoveCallbacks(IBallControlsActions instance)
        {
            if (m_Wrapper.m_BallControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBallControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_BallControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BallControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BallControlsActions @BallControls => new BallControlsActions(this);
    public interface IBallControlsActions
    {
        void OnDownSprint(InputAction.CallbackContext context);
    }
}
